### ISSUE TITLE
Big push in 2018

### ISSUE THREAD

**Issue by cdsouthan** [OpenSourceMalaria/OSMSeries4Paper1#16]
Lets get going....

**Comment by mattodd** [comment]
:) Couldn't agree more, and was discussing this very thing with @edwintse yesterday. Clearly there's a blockage, which could be something as simple as the need for us to do more writing, to which people will respond. I'd be interested to know your thoughts (and those of others) on whether there are baby steps we can take, piecemeal, to kick-start writing in a more distributed effort? i.e. any concrete suggestions for things people could be doing? [I have been trying to chip away at sections we're likely to need on mechanism of action etc](https://docs.google.com/document/d/1vlOHNo9bxmx24KmNdJz5ZmjXyVP9uZoHJcnGj181NZE/edit), and you will notice a nice new section on metabolomic data that has been inserted from Darren Creek's lab. Perhaps there are other paragraphs that we are inevitably going to need that people could suggest are written?

In my view a key issue is whether we try to publish a subset of compounds as a communication, to get across the main points of the series, as per #15. I'm warming to the idea, since then we would focus in on a smaller set of compounds to "complete" for the paper - and in which case our first consideration is which (e.g. subset of ca. 50) compounds is the focus? In either case it seems to me we need to gain clarity on the Pfizer compound (OpenSourceMalaria/Series4#20). If this compound is active, and has the structure we think it has, I'd suggest that the compound could form a key part of a "punchline" for a communication. If it does not, and we have no clarity, perhaps the case for a communication is lessened.

**Comment by cdsouthan** [comment]
Good to generate momentum but I am against any salami-slicing (I see a lot of it in our curation work for the Guide to Pharmacology http://www.guidetopharmacology.org/

**Comment by holeung** [comment]
I've edited and added in some text and suggestions along with a few potential figures. Where are we submitting?

**Comment by cdsouthan** [comment]
As mentioned, we should still be welcome at ACS Central Science, especially since not many of their other papers are likely to hit an Altmetric of 205.  BTW @holeung you mentioned an AI conference on Twitter.  Could we jump on the bandwagon with our S4 data?  Would not be a log roll for me but maybe you and others could pitch in?

**Comment by holeung** [comment]
ACS Central Science sounds great. Yes, I'll be happy to do some ML analysis of S4 data. I'm currently doing that with the S3 data.

**Comment by cdsouthan** [comment]
Fine, and some fancy 3D overlays with coloured sausages?

**Comment by holeung** [comment]
Of course!
