### ISSUE TITLE
Finishing the S4 paper

### ISSUE THREAD

**Issue by cdsouthan** [OpenSourceMalaria/OSMSeries4Paper1#30]
Would be a good time to do this with current wet-work stop  @mattodd @danaklug

**Comment by danaklug** [comment]
@cdsouthan Definitely. I think @edwintse has been doing a lot of work on this in the past couple of months as well. I just had a look over the paper and from what I can see these are the missing pieces:

- Addressing blanks in highlighted text and comments (I can go through but these may be best addressed by @edwintse or other more senior authors or collaborators.)

- Decide on a graphical abstract (I have made a few versions which are in the repository if anyone would like to have a look, or submit other options.)

- SAR tables/figures. I believe we ultimately landed on figures ( #26 ) which @edwintse was working on but these need to be inserted into the manuscript and the text probably needs to be reworked (happy to help with that if you'd like, Ed!)

- We originally wanted to include some _in vivo_ results on the diol or some other lead compound. Obviously progress on this is on hold. It may be worth further discussion as to whether to just publish without these results.

- Complete methodology and SI. A good time to work on this as you mentioned @cdsouthan.

**Comment by edwintse** [comment]
For the third point - I've just put in the paper what I had been working on for the SAR section previously. I didn't want to remove the existing SAR writeup just yet so the tables and text written by @danaklug have been moved to after the references. We can delete once we're happy with what to include.

The SAR is now split up into 5 sections as shown in the figure. Obviously not every structure is included and I've just pick ones which help describe the SAR more concisely. Summarising each section is in progress. The indented text in blue was originally written by Dana and needs to be incorporated.

I think the metabolism and solubility section needs a similar treatment to reduce the number of tables. Perhaps best to pick out a handful of representative compounds and put the rest in the SI?

Generally for the rest of the paper:
- We need to decide on what to do with the OHOH compound and how to present it if this is still going to be the punchline @mattodd.
- The sections on MoA metabolomics approaches needs to be cut down quite a bit. I'll leave that in the hands of someone more familiar with the work who can summarise it better.
- Not too sure about the inclusion of the computation studies either.

**Comment by danaklug** [comment]
Quick update: I have consolidated the text around Ed's figure. @edwintse if you could maybe give it a read when you get a chance? If all looks good to you we can delete the SAR tables at the bottom of the doc and I can work on cleaning everything up for the SI document (I have copies saved so deleting is fine).

My plan is to work on consolidating the metabolism/solubility section and cleaning up the SI file next as long as I won't be stepping on anyone's toes by doing so!

**Comment by cdsouthan** [comment]
Good, 

N.b as mentioned earlier I suggest uploading the entire S4 data sheet to figshare to become one of the supp-dat files.   This ensures we would be (more or less)  FAIR from the outset.

**Comment by edwintse** [comment]
Looks good @danaklug!

Re: metabolism/solubility section - I've put in a placeholder image and table just under the section heading with a selection of compounds that we could highlight. See what you think about them and if compounds could be replaced/added to better describe the measured properties.

If the focus is still on the OHOH compound, I think the late-stage biofunctionalisation stuff should be moved as a sort of intro to that section. I've put in some replacement text for that bit (in blue) and a suggested figure (above the existing one) that's more simplified.

**Comment by danaklug** [comment]
@edwintse Great. For your table, I'm not sure about the inclusion of the carboxylic acid compound - it's not active nor is its ADME profile particularly impressive, it's kind of a one-off structurally and the type of clearance data we have on it isn't consistent with the rest of the compounds. May I also suggest adding to this table MMV639565 (the one that has inherited _in vivo_ data) for comparison and MMV670944 (the pyridyl-substituted amide) since it’s got decent clearance and excellent solubility. The rest look good to me.

Agree about moving the biofunctionalization stuff and I think your figure is great so I've removed the old text and figure. My only suggestion would be to maybe add potency values for the compounds in the figure.

**Comment by MedChemProf** [comment]
Dear OSM, I just wanted to let everyone know that I have spent a good deal of time editing the Series 4 [Manuscript](https://docs.google.com/document/d/1vlOHNo9bxmx24KmNdJz5ZmjXyVP9uZoHJcnGj181NZE/edit?pli=1). I did borrow heavily from what everyone previously drafted and also from the various OSM GitHub discussion threads. I did do quite a bit of reformatting of the SAR sections. I was also adding enough additional references that in order for me to track, I ended up placing the full reference within the manuscript at the point it was supposed to be inserted. All of the references are now within the manuscript body in [blue brackets]. 

A good deal of the comments and questions were 6 months to over a year old and it appeared that they were not going to be followed-up on. I tried to address many of the old comments and added a few new comments for sections that I need some of the group expertise with. I did not modify the Abstract/Graphical Abstract and Conclusion yet since I wanted to hear some feedback with all of my other changes before trying to tackle.

Please note, I did make some deep cuts and changes in an effort to try and contribute further to the project and move the paper forward. I realized that I was making some significant changes, so I first archived a copy of the paper on the GitHub site prior to making my changes. I know Google Docs has a history, but I thought it best to archive the paper as it was for all to reference versus trying to use the track changes. So all is not lost.

I hope you all are well and I look forward to hearing feedback to keep the momentum going. I would also be happy to discuss any of the sections via video chat if that might be easier than many text exchanges. I can also set-up a Zoom meeting for a group meeting if desired.

Thanks, Chase

@cdsouthan @edwintse @danaklug @mattodd @alintheopen

**Comment by danaklug** [comment]
> May I also suggest adding to this table MMV639565

Following discussion at Friday's (25/6) editing session, I've checked and there _is_ Monash ADME data on this compund, so I've added it to **Table 1.**
