### ISSUE TITLE
Add in Molecules MK149 and MK155

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSMSeries4Paper1#49]
Two molecules from @maratsydney PhD work should probably go in to the thesis, MK149 and MK155.

- [x] @MedChemProf to modify schemes in paper (and maybe insert a sentence if something comes to mind?)
- [x] @maratsydney to provide characterisation data to @edwintse for the SI document.

<img width="654" alt="Screenshot 2021-03-23 at 14 47 01" src="https://user-images.githubusercontent.com/4386101/112165711-e3788f00-8be6-11eb-8ceb-70392782b18b.png">

**Comment by MedChemProf** [comment]
@mattodd Figure 5 edited to include MK149 (MMV1634428) and text edited to include mention of limited attempts at heteroaromatic phenyl analogs. Figure 7 edited to include both MK148 (MMV1634429) and MK155 (MMV1634435). Text edited to include an expanded discussion of methyl and hydroxymethyl substitution at the northwest benzyl position. Also edited Figure 6 since it was suggested that table could be summarized further. I eliminated a few more SAR points, but directed readers to the SI for an expanded set of analogs in the text.

**Comment by mattodd** [comment]
That's awesome @MedChemProf and @maratsydney - closing this issue.
